### ISSUE TITLE
Problem demonstrating attack

### ISSUE THREAD

**Issue by galleon65** [bethgelab/foolbox#127]
I have a problem demonstrating an attack on images.
I am using the following Google collab [notebook](https://drive.google.com/open?id=1R0khVrxwZ7aeDPltzsJJO5t85ZZWw4Od) with this [image](https://drive.google.com/file/d/1xDUelkf_rbw01Tac3FJzehViGQwQ-8ho/view?usp=sharing)

I was expecting the adversarial example to have changed class.

Can someone help me fix the problem?

Thanks

**Comment by jonasrauber** [comment]
The notebook you linked is just a screenshot, as far as I can see. And it doesn't show all the relevant parts.

Did you compare `np.argmax(model.predictions(image[:, :, ::-1]))` and `np.argmax(model.predictions(adversarial))`? They should be different.

**Comment by galleon65** [comment]
Sorry was confused by the [:, :, ::-1] notation.
I did compute `np.argmax(model.predictions(adversarial[:, :, ::-1]))` which happen to have the same class as `np.argmax(model.predictions(image[:, :, ::-1]))`

`np.argmax(model.predictions(adversarial))` is of the expected class.

foolbox default images is not RGB then?

![foolbox](https://user-images.githubusercontent.com/37184799/38244270-6985a560-373a-11e8-9aad-a9d9638a72c0.JPG)

**Comment by jonasrauber** [comment]
The problem here is the Keras ResNet model that you use. It expects BGR images. Foolbox doesn't care whether it's RGB, but everything we put in and get out will be in the same format.

By using `image[:, :, ::-1]` we give Foolbox a BGR image that it passes along to the ResNet model. Note that Foolbox has no clue whether you passed it an RGB or BGR image. The adversarial returned by the attack is then in the same format as the one passed in, so `adversarial` and `image[:, :, ::-1]` have the same format, namely BGR in this case.
