### ISSUE TITLE
Get number of iterations until fooled

### ISSUE THREAD

**Issue by xerxes01** [bethgelab/foolbox#165]
I am trying to generate adversarial images for my CNN model. I need to output the exact number of iterations it takes for the attack to fool the model. I understand maxiter is a parameter which can be tuned (in say, LBFGS) but I need to return the exact number of iterations (<maxiter) it takes for the attack to happen.

**Comment by jonasrauber** [comment]
You can pass `unpack=False` when calling an attack. Then it returns an `Adversarial` object rather than the actual image. To get the acutal image you can read out the `image` attribute of the `Adversarial` object. In addition, you can however also read out the `_total_prediction_calls ` and `_total_gradient_calls` attributes that should give you all you need.
