### ISSUE TITLE
Potential Feature Request: Expectation over Transformation Attack

### ISSUE THREAD

**Issue by RaffEdwardBAH** [bethgelab/foolbox#191]
One defense that has been discussed before is performing randomized transformations of the input, and [Expectation over Transformations](https://arxiv.org/pdf/1707.07397.pdf) is one counter to this attack. The idea being to simply sample the model for its gradient multiple times, and averaging the gradient estimates to counter the defender using randomized transformations. 

I think this could be implemented with the `ModelWithEstimatedGradients` class in foolbox, but I'm not entirely sure. I was looking to get feedback if this was on the right track - the documentation is a bit light on what exactly the `gradient_estimator` should be returning.

**Comment by wielandbrendel** [comment]
Hey @RaffEdwardBAH sorry for the late response. I think you are on the right track: basically you would need to extend https://github.com/bethgelab/foolbox/blob/master/foolbox/models/wrappers.py#L75-L107 such that it (optionally) passes not self.batch_predictions but self.predictions_and_gradients to the gradient estimator in order to give it access to the gradients of the model. Than it's pretty straight forward to build a new gradient estimator that samples the gradient of the model multiple times and returns an averaged gradient which you can then use with any of the gradient-based attacks.

**Comment by RaffEdwardBAH** [comment]
Hi, maybe I should try and clarify. 

I'm having trouble understating what the objects being passed around are and where they are even set. 

For example, I do not know what kind of object `pred_fn` is, or what the return object of `_gradient_estimator` should look like. I feel like these are pre-requisite to me trying to understand your given outline on modifying the calls and inputs. I didn't see any gradient estimators in the documentation page, so I wasn't sure where to start on that.

**Comment by wielandbrendel** [comment]
Calling the gradient estimator should return the gradient. Also, please take a closer look at https://github.com/bethgelab/foolbox/issues/191 where you'll see that pred_fn is set as self.batch_predictions. Since the wrapper is derived from the Model class, self.batch_predictions is nothing else but the batch_predictions function of the model.

@jonasrauber We should add a documentation on the gradient estimator.

**Comment by RaffEdwardBAH** [comment]
Ok, I was able to get this implemented using the `DifferentiableModelWrapper` instead, thank you! 

On a related note, is there a way to compute the gradients/predictions for images in batches? This would allow for speedups in general, but also for EoT where we know we will be processing many transformed images in order to get a final gradient.

**Comment by jonasrauber** [comment]
For predictions, there is a batch_predictions method. For gradients: not at the moment

**Comment by jonasrauber** [comment]
Seems to be solved
