### ISSUE TITLE
ValueError: too many values to unpack (expected 1) when working with KerasModel

### ISSUE THREAD

**Issue by ronsap123** [bethgelab/foolbox#214]
I load a model.h5 file using the load_model function in keras and try to pass it to a KerasModel
```
model = load_model(model_path)
fmodel = foolbox.models.KerasModel(model, bounds=(0, 255))
```
That however, gives me the following error

```
     63         if predicts == 'probabilities':
     64             if K.backend() == 'tensorflow':
---> 65                 predictions, = predictions.op.inputs
     66                 loss = K.sparse_categorical_crossentropy(
     67                     label_input, predictions, from_logits=True)

ValueError: too many values to unpack (expected 1)
```

**Comment by jonasrauber** [comment]
Looks like your last layer has more than one input, i.e. it’s not a softmax layer. If it represents logits, maybe pass `predicts=logits` to KerasModel.

**Comment by jonasrauber** [comment]
Seems to be solved

**Comment by kizzen** [comment]
I'm having the same issue - not solved

**Comment by mhsamavatian** [comment]
I defined a custom softmax age got the same error. any updates?

**Comment by jonasrauber** [comment]
@kizzen @mhsamavatian Could you please provide some code and the corresponding error message

**Comment by mhsamavatian** [comment]
64         if predicts == 'probabilities':
     65             if K.backend() == 'tensorflow':
---> 66                 predictions, = predictions.op.inputs
     67                 loss = K.sparse_categorical_crossentropy(
     68                     label_input, predictions, from_logits=True)

ValueError: too many values to unpack (expected 1)


It is because I used a custom activation function for VGG network which I defined myself like:

class My_Act(Layer):
...
....
def call(self, inputs):
        .....
       ....

and then I used in my VGG model:

x = My_Act()(x)

When I use predicts='logits' in the attack instantiation this error does not come up obviously because it does not go into the "if predicts == 'probabilities':". Would this be wrong if I do that? 
My custom activation instead of softmax at the end caused that "predictions, = predictions.op.inputs " becomes wrong.

**Comment by jonasrauber** [comment]
Well, if you make your model output logits, then passing `predicts='logits'` is the way to go and probably the easiest solution.

**Comment by eleonoralas** [comment]
> 64 if predicts == 'probabilities':
> 65 if K.backend() == 'tensorflow':
> ---> 66 predictions, = predictions.op.inputs
> 67 loss = K.sparse_categorical_crossentropy(
> 68 label_input, predictions, from_logits=True)
> 
> ValueError: too many values to unpack (expected 1)
> 
> It is because I used a custom activation function for VGG network which I defined myself like:
> 
> class My_Act(Layer):
> ...
> ....
> def call(self, inputs):
> .....
> ....
> 
> and then I used in my VGG model:
> 
> x = My_Act()(x)
> 
> When I use predicts='logits' in the attack instantiation this error does not come up obviously because it does not go into the "if predicts == 'probabilities':". Would this be wrong if I do that?
> My custom activation instead of softmax at the end caused that "predictions, = predictions.op.inputs " becomes wrong.

I have a similar problem. Did you solve the problem?
