### ISSUE TITLE
About the difference 

### ISSUE THREAD

**Issue by AndrewSoul** [bethgelab/foolbox#250]
Hello, I have a question about the difference between original_image and adversial_image.
The example when showing the difference:
          difference / abs(difference).max() * 0.2 + 0.5
Does it intent to make the observation of difference more obvious?

**Comment by wielandbrendel** [comment]
I am unable to understand your question and I don't know where the formula is coming from. Please clarify.

**Comment by AndrewSoul** [comment]
This is part of the code  for imshow the difference. The code is offered by markdown file in your project.

**Comment by wielandbrendel** [comment]
You have to normalise the difference somehow in order to plot it. The easiest thing is to normalise the max (so the difference lies within -1 and 1) and to then shift everything in the [0, 1] region for plotting. That's a very standard way of doing it. You can also plot the difference if you don't normalise by the max, but then the difference might be so small that you basically don't see anything. But that's a subjective choice one has to think about.

**Comment by AndrewSoul** [comment]
Thanks for answering. I get it.
