### ISSUE TITLE
How to return the original image (gracefully) if an attack fails?

### ISSUE THREAD

**Issue by spencerwooo** [bethgelab/foolbox#498]
**Question:** is there a way to return the original image when an attack fails? Currently, foolbox returns a `np.nan` as described here:

> If the attack fails to find an adversarial for the `i`th image, then adversarials[i] will all be `np.nan` -- [Running a batch attack against a PyTorch model](https://foolbox.readthedocs.io/en/stable/user/examples.html#running-a-batch-attack-against-a-pytorch-model)

As for now, I'm implementing this like so:

```python
if np.isnan(adv).any():
  adv = image.numpy()
```

Where `adv` is the adversarial generated and `image.numpy()` is the original image. I don't know if this is the best approach. Thanks.

**Comment by jonasrauber** [comment]
Not really, because Foolbox 1 and 2 guarantee to return adversarials, so they return the original image if that original image is already misclassified. Also, the idea in Foolbox 1 and 2 is to run the attacks such they find the minimal adversarial perturbation, thus at least in principle they should always succeed (maybe with large perturbations) and a failing attack is an indicator of a weak or non-applicable attack.
I think your solution for replacing the adv with the original is fine (though it looks like you are working with single images but at the same time use batch attacks).

In Foolbox 3 all of this is a bit different, because it returns perturbed images and an explicit tensor indicating which perturbed images are adversarial. There some attacks (that try to minimize the perturbation) may return the original image if they fail, but that's not guaranteed (and for attacks that use a fixed perturbation size, that obviously cannot be the case).

**Comment by spencerwooo** [comment]
All right, thanks for the clarification. 💗
