### ISSUE TITLE
L-BFGS target classes fails

### ISSUE THREAD

**Issue by neale** [bethgelab/foolbox#54]
Hi, sorry to bombard you with this:)
I'm having trouble with specifying a target class with L-BFGS with the Resnet example. 

It looks like FGSM is used to determine the closest class by default and then that class is chosen as the target class. This works well

But if the gradient attack fails, I get a random class, and this almost always fails to produce an adversarial with the targeted class. I get a zero (or nearly zero) image, without a warning.  
Of course if I specify a target class, it also fails. 

It looks like its related to this piece of code here in `attacks/base.py` `line 86`
```python
find = Adversarial(model, criterion, image, label)
assert find is not None
adversarial = find
if adversarial.distance.value == 0.:
    warnings.warn('Not running the attack because the original image  is already misclassified and the adversarial thus has a distance of 0.')  #
```
I don't understand what this means fundamentally, since there's no true label passed in beyond the vanilla network prediction. Even if these images are misclassifed, the image can still be moved passed the value surface that it lies in. But I'm sure there is more here that I'm not seeing.

**Comment by wielandbrendel** [comment]
Could you give a minimum working example where this error arises?

**Comment by neale** [comment]
Of course. 
The attack just isn't applied in most cases, I figured it was just my images, but I'm only using the imagenet validation set, so they should be ok as far as that goes. 

Here's the test code in a [gist](https://gist.github.com/neale/d5ed607d00a1ef8b76c704e25bcc70f6)
And here is an offending [image](https://github.com/neale/pup/blob/master/ILSVRC2012_val_00017762.JPEG)

This is with a clean pip install, to rule out my edits.
Thanks again!

**Comment by jonasrauber** [comment]
You calculate the reference label like this:
`label = numpy.argmax(fmodel.predictions(image))`,
i.e. with RGB color channel ordering, but the network expects BGR and you also use BGR when running the attack: `adversarial = attack(image[:,:,::-1], label, unpack=False)`
Therefore, the reference label and the prediction for the input image made by the attack differ and the original image is _misclassified_.

In other words: just use `label = numpy.argmax(fmodel.predictions(image[:, :, ::-1]))` to get the reference label.

However, I think Foolbox should abstract away the color channel ordering (RGB vs. BGR) as part of the preprocessing so that the user does not run into these issues. I will probably add this to the next Foolbox release. Thanks @neale!


P.S.: when I run the code in your gist, I do get a warning that helped me track down this problem:
> .../foolbox/attacks/base.py:93: UserWarning: Not running the attack because the original image is already misclassified and the adversarial thus has a distance of 0.

Do you get this warning as well, @neale, or is it hidden because of your python configuration? In that case, it would be good to know so that we can make sure that users see the warnings.

**Comment by wielandbrendel** [comment]
@jonasrauber How do you want to abstract channel ordering away? I wouldn't like to introduce anything that is specific to "color channels". Quite the contrary, I'd even like to get rid of the color_channel argument as it is too specific too images. One could nonetheless make it part of the preprocessing in that one can define channel flipping with an additional argument of the type [1,1,-1] (so in this case the spatial axes would not be flipped but the color channel would).

**Comment by jonasrauber** [comment]
For now, I will add a `reverse_channel_order` argument (at first I thought about adding a way to specify RGB / BGR, but I also thought that's too image specific). I think the notion of "channels" is general enough for now: we have channel_axis (it's not called color_channel ;-) ) anyway and cannot easily get rid of it, and every ConvNet (not just for images) has that notion. 
If we at some point really get rid of channel_axis and other channel related stuff, we might want to think about a more general preprocessing anyway.

**Comment by wielandbrendel** [comment]
But where is channel_axis actually being used? As far as I can see it's only used in two or three attacks, right?

**Comment by jonasrauber** [comment]
True, some attacks (don't know how many). But let's have this discussion somewhere else.

@neale If your problem is solved, just close the issue.

**Comment by neale** [comment]
Thanks!
