### ISSUE TITLE
[JOSS Review] Example usage

### ISSUE THREAD

**Issue by GregaVrbancic** [bethgelab/foolbox#586]
Hi @jonasrauber, I went through [the example using tensorflow](https://github.com/bethgelab/foolbox/blob/master/examples/tensorflow_resnet50.py) and while I did not have any issues running the code, I think it would be beneficial if the provided examples would be more clearly named, so the users could find the right example more easily. Additionally, I would also appreciate a few sentences in the examples on the topic of how to interpret the output results. This way the tool would be also more attractive to potential users who are not so familiar with the topic.

I also noticed, that there is a tutorial in a form of a jupyter notebook. Maybe it could be a bit more emphasized in the readme page so it can be found more easily, and also I think that the notebook tutorial would benefit a lot if you would improve it by adding a bit of results interpretation.

**Comment by jonasrauber** [comment]
Thanks for the feedback.
I have updated the examples to contain more comments and explanations, renamed them to be more consistent and explicit, and added a README to the examples folder (https://github.com/bethgelab/foolbox/pull/590).
Furthermore, I have updated the Jupyter notebook to include some explanations of the results and I added a direct link to open the notebook in Google Colab to the the main README (that gives it additional visibility, because the link is an image).
