### ISSUE TITLE
About the except with did not find an adversarial

### ISSUE THREAD

**Issue by shenqixiaojiang** [bethgelab/foolbox#63]
When the attack function can't get the adversarial, the None will be return.  
But I think the original image should be return not the None since sometimes we want to get an image.

**Comment by wielandbrendel** [comment]
That would be pretty confusing: you expect the return to be an adversarial, but the original image would not be one. Returning None in cases where no adversarial was found is a loud and clear warning that, well, no adversarial was found ;-). In other words: you don't just want to display some image no matter what, but you only want to display adversarial images after the attack. Which means you'll necessarily have to deal with cases where the attack failed.

**Comment by shenqixiaojiang** [comment]
Ok, it makes sense to me.  So maybe you can say something in the example when the return is None.

**Comment by wielandbrendel** [comment]
We should probably issue a warning if an attack fails. @jonasrauber What do you think?

**Comment by ecobost** [comment]
Hi guys, 
Thanks for the toolbox. 
It already prints a warning when the attack fails but maybe you could document in `base.Attack.__call__` what is the expected output for images who are already misclassified and for failed adversarials (original image and None). 
When the attack fails, having it return None is slightly inconvenient if you are generating a set of adversarial images, which I assume is the main use case for foolbox. For instance, this:
```python
    adversarials = np.empty_like(clean_images)
    for i, (image, label) in enumerate(zip(clean_images, clean_labels)):
        adversarials[i] = attack(image, label)
```
does not fail but fills the failed image attacks with nans. If you are not aware of attack possibly returning None you could think the nans are numerical errors or come from a different source. In fact, in pytorch a nan image can go through the network, preds will be nans and argmax will be zero so if you try to compute accuracy in this set it will work fine but the number will be wrong. If the original image is returned, this will work alright. The workaround is of course easy (just check for None) but it may catch people off-guard.
Cheers,

**Comment by wielandbrendel** [comment]
@ecobost Thanks for your perspective! I wasn't aware that array[i] = None would insert NaNs and I can see your point. On the other hand, returning the original image would be even more confusing, right? At least this way you are warned that something went wrong. So either we stay with None (and add a better description) or we actually raise an Error (we could add a "NoAdversarialFoundError"). That would force the user to handle that case more carefully. Right now I am leaning towards the latter. What do you think @shenqixiaojiang @ecobost @jonasrauber ?

**Comment by shenqixiaojiang** [comment]
@wielandbrendel Yeah， stay with None is good and I think you should give a explain in the example. Like the following:

attack  = foolbox.attacks.FGSM(fmodel)
#if adversarial  == None which means the adversarial example can't be found, you should deal this except by yourself.
adversarial = attack(image[:,:,::-1], label)

As for me, I want to get the successful rate of attacking example, so the original image is suggested to return.
So I can deal the except with: 

if adversarial  == None:
     adversarial  = image

**Comment by jonasrauber** [comment]
Just to clarify things a bit: we are talking about three different cases here:

1. the original image is correctly classified and the attack finds an adversarial:

- the adversarial is returned
- no warning produced
- no exception thrown

2. the original image already fulfills the _criterion_ for an adversarial (e.g. is misclassified or classified as some target class, etc.) and therefore the attack is not executed

- the original image is returned as the adversarial
- a UserWarning is produced to make the user aware of this special case
- no exception is thrown

3. the original image is correctly classified but the attack does not find an adversarial

- None is returned
- a UserWarning is produced to make it more obvious to the user, especially during interactive usage
- no exception is thrown


Now I think everyone is fine with 1.
For 2. and 3. one can discuss whether it's more appropriate to throw an error instead of returning the original image (2. case) or None (3. case). I think we have four options:

a) leave everything as is
b) only change the 2. case to throw an error instead of returning something
c) only change the 3. case to throw an error instead of returning something
d) change the 2. and 3. case to throw errors instead of returning something

For the 2. case, it's a question of how one defines **adversarial**, i.e. whether one is okay with treating original images as adversarials if they fulfill the _criterion_, despite not being close to a correctly classified image. If yes then returning the original image is correct behavior, if no (more traditional view on adversarials) then an error should be thrown.

For the 3. case, it's a question of whether one thinks of failing attacks as something exceptional that should usually not happen (should thrown an error) or as something normal (should return None).


In Python, both semantics (returning a special value like None or the original image vs. throwing an error) are common and accepted; afaik there is no preferred _pythonic_ way. My impression is that people usually prefer special return values (e.g. None) because they seem easier to handle, but at the same time, exceptions are more explicit and enforce a response from the user.


At the moment, I think I have a slight preference for _throwing errors_, but I am not decided. It would make non-interactive usage more verbose:

```python3
try:
    adversarial = attack(image, label)
except OriginalImageIsAdversarial:
    adversarial = image  # for example; user has the ability to handle this differently
except NoAdversarialFound:
    # handle failed attack ...
```

instead of

```python3
adversarial = attack(image, label)
if adversarial is None:
    # handle failed attack ...
```

**Comment by wielandbrendel** [comment]
I think I am also leaning towards throwing an error when an attack fails. At the same time I would not throw an error when the original image is an adversarial as that is totally acceptable under the given criterion.

**Comment by jonasrauber** [comment]
I added a comment to the main example in the Readme. If you think we should document this somewhere else as well, let me know.

Throwing exceptions in this case would be breaking change; we will consider making this change for 2.0, but for now, I will close this.
