### ISSUE TITLE
Not matching with the number of labels

### ISSUE THREAD

**Issue by Changgun-Choi** [bethgelab/foolbox#682]
Hello, 
Q. The issue while using custom dataset.

I am using simple dataset, 'Cifar10' which has 10 labels however, output of model(images) has 1000 dimensions and as a result, prediction has 1000 labels that do not match.

![image](https://user-images.githubusercontent.com/72928938/162082248-fc59bedb-5ef3-4f2d-9fdd-bf9d2881a270.png)
Please let me know about this issue!
Thank you again.

**Comment by jangop** [comment]
Your model has probably not been trained for CIFAR-10. My guess is ImageNet, because of the number of classes.

I cannot be sure, because your screenshot does not show a working example.

Please do not post screenshots of code and instead provide text as text.

This issue does not seem to be related to Foolbox.
