### ISSUE TITLE
Example code: Foolbox model predicts different class than underlying Keras model

### ISSUE THREAD

**Issue by Sponn** [bethgelab/foolbox#92]
In the example code provided on GitHub the Foolbox model predicts class 282 for the example image using Keras and ResNet50. 
If you let the underlying Keras model predict the class with

np.argmax(kmodel.predict(image[None,:])

it returns 287. I think this is beacause of the preprocessing done in the Foolbox model. Without said preprocessing both models return class 287. 
Why is this example image used if ResNet50 seems to be unable to classify it correctly without applying some seemingly arbitrary preprocessing?

**Comment by wielandbrendel** [comment]
I am not sure what your question is. Certain preprocessing steps (e.g. subtracting the average channel activation) are standard but often these steps are not part of the model but have to be applied manually. You could do the preprocessing on your own but when it comes to optimising adversarial examples you run into a problem because the bounds on the input activations usually apply only to the unprocessed image. That's why Foolbox has to know about the preprocessing steps.

**Comment by Sponn** [comment]
I got this wrong then. Thanks for clearing this up so quickly!
